services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cp config/config.example.php config/config.php
  - chmod +x bin/slim-rbac
  - composer update

language: php
php:
  - '5.4'
script:
  - ./bin/slim-rbac migrate --cli-path=config/cli-config.php
  - vendor/bin/codecept run
  
